basePath: /
definitions:
  models.CreateNoteSchema:
    properties:
      category:
        type: string
      content:
        type: string
      published:
        type: boolean
      title:
        type: string
    required:
    - content
    - title
    type: object
  models.Note:
    properties:
      category:
        type: string
      content:
        type: string
      createdAt:
        type: string
      id:
        type: string
      published:
        type: boolean
      title:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8000
info:
  contact:
    email: fiber@swagger.io
    name: API Support
  description: This is a sample swagger for Fiber
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Example API
  version: "1.0"
paths:
  /api/notes:
    get:
      description: Find a Note
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Note'
            type: array
        "400":
          description: Bad Request
          schema: {}
      summary: Find Note
      tags:
      - Notes
    post:
      consumes:
      - application/json
      description: Create a new note with the provided data
      parameters:
      - description: Note Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/models.CreateNoteSchema'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Note'
        "400":
          description: Bad Request
          schema: {}
      summary: Create a new note
      tags:
      - Notes
swagger: "2.0"
